apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-05-20T14:58:19Z
  name: dev.hub.tikal.io
spec:
  api:
    dns: {}
  addons:
  - manifest: kubernetes-dashboard
  - manifest: monitoring-standalone
  - manifest: cluster-autoscaler
  - manifest: logging-elasticsearch
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://ac.fuse.tikal.io/dev.hub.tikal.io
  dnsZone: hub.tikal.io
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterPublicName: api.dev.hub.tikal.io
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
